# Generated by Django 4.1.1 on 2022-09-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_room_category_alter_room_owner"),
        ("experiences", "0003_alter_experience_category_alter_experience_owner"),
        ("wishlists", "0002_alter_wishlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="experinces",
            field=models.ManyToManyField(blank=True, to="experiences.experience"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="rooms",
            field=models.ManyToManyField(blank=True, to="rooms.room"),
        ),
    ]
